-- MySQL Script generated by MySQL Workbench
-- Sun Jan  9 13:35:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema youtube_inma_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtube_inma_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube_inma_db` DEFAULT CHARACTER SET utf8 ;
USE `youtube_inma_db` ;

-- -----------------------------------------------------
-- Table `youtube_inma_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`usuarios` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` ENUM('Masculino', 'Femenino') NOT NULL DEFAULT 'Femenino',
  `pais` VARCHAR(50) NOT NULL,
  `cp` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`canales` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NULL DEFAULT NULL,
  `nombre_canal` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `canales_usuarios_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`videos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `estado_video` ENUM('Público', 'Privado', 'Oculto') NOT NULL DEFAULT 'Público',
  `titulo` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `tamano` FLOAT NOT NULL,
  `nombre_archivo_video` VARCHAR(50) NOT NULL,
  `duracion` DOUBLE NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(50) NOT NULL,
  `reproducciones_num` INT(11) UNSIGNED NOT NULL,
  `likes_num` INT(11) UNSIGNED NOT NULL,
  `dislikes_num` INT(11) UNSIGNED NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `videos_usuarios_fk` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `videos_usuarios_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`comentarios` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_video` INT(11) UNSIGNED NOT NULL,
  `texto_comentario` VARCHAR(255) NOT NULL,
  `fecha_comentario` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `comentarios_usuarios_fk` (`id_usuario` ASC) VISIBLE,
  INDEX `comentarios_videos_fk` (`id_video` ASC) VISIBLE,
  CONSTRAINT `comentarios_usuarios_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`),
  CONSTRAINT `comentarios_videos_fk`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube_inma_db`.`videos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`etiquetas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_etiqueta` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`playlists` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `nombre_playlist` VARCHAR(50) NOT NULL,
  `estado_playlist` ENUM('Pública', 'Privada') NOT NULL DEFAULT 'Pública',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `playlists_usuario_fk` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `playlists_usuario_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`usuarios_opinion_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`usuarios_opinion_comentarios` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_comentario` INT(11) UNSIGNED NOT NULL,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `fecha_comentario` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `opinion_comentario` ENUM('Me gusta', 'No me gusta') NOT NULL DEFAULT 'Me gusta',
  PRIMARY KEY (`id`),
  INDEX `usuarios_videos_comentarios_usuarios_fk` (`id_usuario` ASC) VISIBLE,
  INDEX `usuarios_videos_comentarios_videos__fk` (`id_comentario` ASC) VISIBLE,
  CONSTRAINT `usuarios_videos_comentarios_usuarios_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`),
  CONSTRAINT `usuarios_videos_comentarios_videos__fk`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `youtube_inma_db`.`comentarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`usuarios_suscripcion_canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`usuarios_suscripcion_canales` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_canal` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `usuarios_canales_canales_fk` (`id_canal` ASC) VISIBLE,
  INDEX `usuarios_fk` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `canales_fk`
    FOREIGN KEY (`id_canal`)
    REFERENCES `youtube_inma_db`.`canales` (`id`),
  CONSTRAINT `usuarios_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`usuarios_videos_valoraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`usuarios_videos_valoraciones` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_video` INT(11) UNSIGNED NOT NULL,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `fecha_valoracion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `valoracion` ENUM('like', 'dislike') NOT NULL DEFAULT 'like',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `id_video_usuario` (`id_video` ASC, `id_usuario` ASC) VISIBLE,
  INDEX `id_video` (`id_video` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `usuarios_valoracion_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube_inma_db`.`usuarios` (`id`),
  CONSTRAINT `usuarios_videos_valoraciones_fk`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube_inma_db`.`videos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`videos_etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`videos_etiquetas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_video` INT(11) UNSIGNED NOT NULL,
  `id_etiqueta` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_video_etiqueta` (`id_video` ASC, `id_etiqueta` ASC) VISIBLE,
  INDEX `videos_etiquetas_etiquetas_fk` (`id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `videos_etiquetas_etiquetas_fk`
    FOREIGN KEY (`id_etiqueta`)
    REFERENCES `youtube_inma_db`.`etiquetas` (`id`),
  CONSTRAINT `videos_etiquetas_videos_fk`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube_inma_db`.`videos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube_inma_db`.`videos_playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube_inma_db`.`videos_playlists` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_video` INT(11) UNSIGNED NOT NULL,
  `id_playlist` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `playlists_fk` (`id_playlist` ASC) VISIBLE,
  INDEX `playlists_videos_fk` (`id_video` ASC) VISIBLE,
  CONSTRAINT `playlists_fk`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `youtube_inma_db`.`playlists` (`id`),
  CONSTRAINT `playlists_videos_fk`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube_inma_db`.`videos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
