-- MySQL Script generated by MySQL Workbench
-- Sun Jan  9 13:11:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optica_inma_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica_inma_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica_inma_db` DEFAULT CHARACTER SET utf8 ;
USE `optica_inma_db` ;

-- -----------------------------------------------------
-- Table `optica_inma_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`clientes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente_recomendado` INT(11) UNSIGNED NULL DEFAULT '0',
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_cliente_recomendado_FK` (`id_cliente_recomendado` ASC) VISIBLE,
  CONSTRAINT `id_cliente_recomendado_FK`
    FOREIGN KEY (`id_cliente_recomendado`)
    REFERENCES `optica_inma_db`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`empleados` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido_primero` VARCHAR(50) NOT NULL DEFAULT '0',
  `apellido_segundo` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`gafas_color_montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`gafas_color_montura` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color_montura` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`proveedores` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `telefono` INT(9) NOT NULL DEFAULT '0',
  `fax` INT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nif` (`nif` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`marcas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT(11) UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `marca_proveedor_fk`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `optica_inma_db`.`proveedores` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`gafas_monturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`gafas_monturas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_montura` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`gafas_vidrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`gafas_vidrios` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `vidrio_color` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`gafas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_marca` INT(11) UNSIGNED NOT NULL,
  `id_gafa_montura` INT(11) UNSIGNED NOT NULL,
  `id_gafa_color_montura` INT(11) UNSIGNED NOT NULL,
  `id_gafa_vidrio` INT(11) UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `graduacion` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `precio` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_marca` (`id_marca` ASC) VISIBLE,
  INDEX `gafa_color_montura_fk_3` (`id_gafa_color_montura` ASC) VISIBLE,
  INDEX `gafa_tipo_montura_fk_2` (`id_gafa_montura` ASC) VISIBLE,
  INDEX `gafa_vidrio_gafas_fk_4` (`id_gafa_vidrio` ASC) VISIBLE,
  CONSTRAINT `gafa_color_montura_fk_3`
    FOREIGN KEY (`id_gafa_color_montura`)
    REFERENCES `optica_inma_db`.`gafas_color_montura` (`id`),
  CONSTRAINT `gafa_marca_fk_1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `optica_inma_db`.`marcas` (`id`),
  CONSTRAINT `gafa_tipo_montura_fk_2`
    FOREIGN KEY (`id_gafa_montura`)
    REFERENCES `optica_inma_db`.`gafas_monturas` (`id`),
  CONSTRAINT `gafa_vidrio_gafas_fk_4`
    FOREIGN KEY (`id_gafa_vidrio`)
    REFERENCES `optica_inma_db`.`gafas_vidrios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica_inma_db`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica_inma_db`.`ventas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_gafa` INT(11) UNSIGNED NOT NULL,
  `id_cliente` INT(11) UNSIGNED NOT NULL,
  `id_empleado` INT(11) UNSIGNED NOT NULL,
  `fecha_venta` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_gafa` (`id_gafa` ASC) VISIBLE,
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `venta_cliente_fk`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `optica_inma_db`.`clientes` (`id`),
  CONSTRAINT `venta_empleado_fk`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `optica_inma_db`.`empleados` (`id`),
  CONSTRAINT `venta_gafa_fk`
    FOREIGN KEY (`id_gafa`)
    REFERENCES `optica_inma_db`.`gafas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
