-- MySQL Script generated by MySQL Workbench
-- Mon Jan  3 13:12:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spotify_inma_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify_inma_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify_inma_db` DEFAULT CHARACTER SET utf8 ;
USE `spotify_inma_db` ;

-- -----------------------------------------------------
-- Table `spotify_inma_db`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`album` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `año_publicacion` YEAR(4) NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`artistas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_album` INT(11) UNSIGNED NOT NULL,
  `nombre_artista` VARCHAR(50) NOT NULL,
  `imagen_artista` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `artista_album_fk` (`id_album` ASC) VISIBLE,
  CONSTRAINT `artista_album_fk`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify_inma_db`.`album` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`artistas_relacionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`artistas_relacionados` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_artista` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `artista_fk` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `artista_fk`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify_inma_db`.`artistas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`canciones` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_album` INT(11) UNSIGNED NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `duracion` TIME NOT NULL,
  `numero_reproducciones` INT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `album` (`id_album` ASC) VISIBLE,
  CONSTRAINT `album`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify_inma_db`.`album` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`forma_pago` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `forma_pago` ENUM('Paypal', 'Tarjeta') NOT NULL DEFAULT 'Paypal',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`playlists_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`playlists_estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` ENUM('Activa', 'Eliminada') NOT NULL DEFAULT 'Activa',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_tipo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Free', 'Premium') NOT NULL DEFAULT 'Free',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuarios_tipo` INT(11) UNSIGNED NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` ENUM('Femenino', 'Masculino', 'Neutro') NOT NULL DEFAULT 'Femenino',
  `pais` VARCHAR(50) NOT NULL,
  `cp` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarios_tipo_fk` (`id_usuarios_tipo` ASC) VISIBLE,
  CONSTRAINT `usuarios_tipo_fk`
    FOREIGN KEY (`id_usuarios_tipo`)
    REFERENCES `spotify_inma_db`.`usuarios_tipo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`playlists` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_playlist_estado` INT(11) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `numero_canciones` INT(255) UNSIGNED NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_eliminacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `playlist_estado_fk` (`id_playlist_estado` ASC) VISIBLE,
  INDEX `usuario_playlist_fk` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `playlist_estado_fk`
    FOREIGN KEY (`id_playlist_estado`)
    REFERENCES `spotify_inma_db`.`playlists_estado` (`id`),
  CONSTRAINT `usuario_playlist_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`playlists_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`playlists_canciones` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario_add` INT(11) UNSIGNED NOT NULL,
  `id_playlist` INT(11) UNSIGNED NOT NULL,
  `id_cancion` INT(11) UNSIGNED NOT NULL,
  `fecha_add` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `playlist_fk` (`id_playlist` ASC) VISIBLE,
  INDEX `usuario_add_canciones_fk` (`id_usuario_add` ASC) VISIBLE,
  INDEX `cancion_fk` (`id_cancion` ASC) VISIBLE,
  CONSTRAINT `cancion_fk`
    FOREIGN KEY (`id_cancion`)
    REFERENCES `spotify_inma_db`.`canciones` (`id`),
  CONSTRAINT `playlist_fk`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `spotify_inma_db`.`playlists` (`id`),
  CONSTRAINT `usuario_add_canciones_fk`
    FOREIGN KEY (`id_usuario_add`)
    REFERENCES `spotify_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_artistas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_artista` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_artistas_fk` (`id_usuario` ASC) VISIBLE,
  INDEX `usuario_artistas_fk_1` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `usuario_artistas_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify_inma_db`.`usuarios` (`id`),
  CONSTRAINT `usuario_artistas_fk_1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify_inma_db`.`artistas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_favoritas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_favoritas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cancion` INT(11) UNSIGNED NULL DEFAULT NULL,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_album` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cancion_fav_fk` (`id_cancion` ASC) VISIBLE,
  INDEX `usuario_fav_fk` (`id_usuario` ASC) VISIBLE,
  INDEX `album_fav_fk` (`id_album` ASC) VISIBLE,
  CONSTRAINT `album_fav_fk`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify_inma_db`.`album` (`id`),
  CONSTRAINT `cancion_fav_fk`
    FOREIGN KEY (`id_cancion`)
    REFERENCES `spotify_inma_db`.`canciones` (`id`),
  CONSTRAINT `usuario_fav_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_suscripcion` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_forma_pago` INT(11) UNSIGNED NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_renovacion` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `forma_pago_fk` (`id_forma_pago` ASC) VISIBLE,
  CONSTRAINT `forma_pago_fk`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `spotify_inma_db`.`forma_pago` (`id`),
  CONSTRAINT `usuario_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify_inma_db`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_forma_pago_paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_forma_pago_paypal` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario_suscripcion` INT(10) UNSIGNED NOT NULL,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_suscripcion` (`id_usuario_suscripcion` ASC) VISIBLE,
  CONSTRAINT `usuario_suscripcion_paypal_fk`
    FOREIGN KEY (`id_usuario_suscripcion`)
    REFERENCES `spotify_inma_db`.`usuarios_suscripcion` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_forma_pago_tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_forma_pago_tarjeta` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario_suscripcion` INT(11) UNSIGNED NOT NULL,
  `numero_tarjeta` VARCHAR(20) NOT NULL,
  `caducidad` DATE NOT NULL,
  `cvc` VARCHAR(3) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_suscripcion` (`id_usuario_suscripcion` ASC) VISIBLE,
  CONSTRAINT `usuario_suscripcion_tarjeta_fk`
    FOREIGN KEY (`id_usuario_suscripcion`)
    REFERENCES `spotify_inma_db`.`usuarios_suscripcion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify_inma_db`.`usuarios_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_inma_db`.`usuarios_pago` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario_suscripcion` INT(11) UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `orden` VARCHAR(50) NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_suscripcion` (`id_usuario_suscripcion` ASC, `orden` ASC) VISIBLE,
  CONSTRAINT `usuarios_pago_fk`
    FOREIGN KEY (`id_usuario_suscripcion`)
    REFERENCES `spotify_inma_db`.`usuarios_suscripcion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
