-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 13:32:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria_inma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria_inma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria_inma` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria_inma` ;

-- -----------------------------------------------------
-- Table `pizzeria_inma`.`ubicacion_localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`ubicacion_localidades` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`ubicacion_provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`ubicacion_provincias` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_localidad` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_localidad` (`id_localidad` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`clientes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_localidad` INT(11) UNSIGNED NOT NULL,
  `id_provincia` INT(11) UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL DEFAULT '0',
  `apellido_primero` VARCHAR(255) NOT NULL,
  `apellido_segundo` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `cp` VARCHAR(50) NOT NULL,
  `telefono` INT(9) NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_cliente` USING BTREE (`id`) VISIBLE,
  INDEX `cliente_localidad_FK_1` (`id_localidad` ASC) VISIBLE,
  INDEX `cliente_provincia_FK_2` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `cliente_localidad_FK_1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria_inma`.`ubicacion_localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_provincia_FK_2`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria_inma`.`ubicacion_provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`tiendas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_localidad` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_provincia` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_pedido` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_empleado` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `direccion` VARCHAR(255) NOT NULL DEFAULT '0',
  `cp` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `tiendas_provincias_FK_2` (`id_provincia` ASC) VISIBLE,
  INDEX `tiendas_localidades_FK_1` (`id_localidad` ASC) VISIBLE,
  INDEX `tiendas_pedidos_FK_3` (`id_pedido` ASC) VISIBLE,
  INDEX `tiendas_empleados_FK_4` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `tiendas_localidades_FK_1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria_inma`.`ubicacion_localidades` (`id`),
  CONSTRAINT `tiendas_provincias_FK_2`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria_inma`.`ubicacion_provincias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`empleados_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`empleados_tipo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`empleados` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_empleado_tipo` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_tienda` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre` VARCHAR(50) NOT NULL DEFAULT '0',
  `apellido_primero` VARCHAR(50) NOT NULL DEFAULT '0',
  `apellido_segundo` VARCHAR(50) NOT NULL DEFAULT '0',
  `nif` VARCHAR(50) NOT NULL DEFAULT '0',
  `telefono` INT(9) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `empleados_tiendas_FK_1` (`id_tienda` ASC) VISIBLE,
  INDEX `empleados_tipo_de_empleados_FK_2` (`id_empleado_tipo` ASC) VISIBLE,
  CONSTRAINT `empleados_tiendas_FK_1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_inma`.`tiendas` (`id`),
  CONSTRAINT `empleados_tipo_de_empleados_FK_2`
    FOREIGN KEY (`id_empleado_tipo`)
    REFERENCES `pizzeria_inma`.`empleados_tipo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`empleados_reparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`empleados_reparto` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_empleado` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `empleados_reparto_empleados_FK` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `empleados_reparto_empleados_FK`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `pizzeria_inma`.`empleados` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`pedidos_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`pedidos_tipo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`pedidos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tienda` INT(11) UNSIGNED NOT NULL,
  `id_cliente` INT(11) UNSIGNED NOT NULL,
  `id_pedido_tipo` INT(11) UNSIGNED NOT NULL,
  `id_empleado_reparto` INT(11) UNSIGNED NULL DEFAULT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `cantidad_producto` INT(11) UNSIGNED NOT NULL,
  `precio_total` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `pedido_cliente_FK_1` (`id_cliente` ASC) VISIBLE,
  INDEX `pedido_tipo_entrega_FK_2` (`id_pedido_tipo` ASC) VISIBLE,
  INDEX `pedidos_tiendas_FK_4` (`id_tienda` ASC) VISIBLE,
  INDEX `pedidos_empleados_FK_3` (`id_empleado_reparto` ASC) VISIBLE,
  CONSTRAINT `pedidos_cliente_FK_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria_inma`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pedidos_empleados_FK_3`
    FOREIGN KEY (`id_empleado_reparto`)
    REFERENCES `pizzeria_inma`.`empleados_reparto` (`id`),
  CONSTRAINT `pedidos_tiendas_FK_4`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_inma`.`tiendas` (`id`),
  CONSTRAINT `pedidos_tipo_entrega_FK_2`
    FOREIGN KEY (`id_pedido_tipo`)
    REFERENCES `pizzeria_inma`.`pedidos_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`productos_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`productos_tipo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`productos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_producto` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_pedido` INT(11) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL DEFAULT '',
  `descripcion` VARCHAR(255) NOT NULL DEFAULT '',
  `imagen` VARCHAR(255) NOT NULL DEFAULT '',
  `precio` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `producto_tipos_de_productos_FK_1` (`id_tipo_producto` ASC) VISIBLE,
  INDEX `productos_pedidos_FK_2` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `producto_tipos_de_productos_FK_1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `pizzeria_inma`.`productos_tipo` (`id`),
  CONSTRAINT `productos_pedidos_FK_2`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria_inma`.`pedidos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`pedidos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`pedidos_productos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pedido` INT(11) UNSIGNED NOT NULL,
  `id_producto` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_producto_fk` (`id_producto` ASC) VISIBLE,
  INDEX `id_pedido_fk` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `id_pedido_fk`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria_inma`.`pedidos` (`id`),
  CONSTRAINT `id_producto_fk`
    FOREIGN KEY (`id_producto`)
    REFERENCES `pizzeria_inma`.`productos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`productos_pizza_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`productos_pizza_categorias` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`productos_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`productos_pizza` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_producto_tipo` INT(11) UNSIGNED NOT NULL,
  `id_producto_pizza_categoria` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre_pizza` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `pizzas_productos_categorias_FK_2` (`id_producto_pizza_categoria` ASC) VISIBLE,
  INDEX `pizzas_productos_tipos_de_productos_FK_1` (`id_producto_tipo` ASC) VISIBLE,
  CONSTRAINT `pizzas_productos_categorias_FK_2`
    FOREIGN KEY (`id_producto_pizza_categoria`)
    REFERENCES `pizzeria_inma`.`productos_pizza_categorias` (`id`),
  CONSTRAINT `pizzas_productos_tipos_de_productos_FK_1`
    FOREIGN KEY (`id_producto_tipo`)
    REFERENCES `pizzeria_inma`.`productos_tipo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
