-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 12:22:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria_inma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria_inma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria_inma` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria_inma` ;

-- -----------------------------------------------------
-- Table `pizzeria_inma`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`categorias` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`provincias` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_localidad` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre_provincia` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `id_localidad` (`id_localidad` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`localidades` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_localidad` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `id_localidad` (`id` ASC),
  CONSTRAINT `localidades_provincias_FK_1`
    FOREIGN KEY (`id`)
    REFERENCES `pizzeria_inma`.`provincias` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`clientes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL DEFAULT '0',
  `apellido_1` VARCHAR(255) NOT NULL,
  `apellido_2` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `cp` VARCHAR(50) NOT NULL,
  `id_localidad` INT(11) UNSIGNED NOT NULL,
  `id_provincia` INT(11) UNSIGNED NOT NULL,
  `telefono` INT(9) NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_cliente` USING BTREE (`id`) VISIBLE,
  INDEX `cliente_localidad_FK_1` (`id_localidad` ASC) VISIBLE,
  INDEX `cliente_provincia_FK_2` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `cliente_localidad_FK_1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria_inma`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_provincia_FK_2`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria_inma`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`tiendas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NOT NULL DEFAULT '0',
  `cp` VARCHAR(50) NOT NULL DEFAULT '0',
  `id_localidad` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_provincia` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_pedido` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_empleado` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `tiendas_provincias_FK_2` (`id_provincia` ASC) VISIBLE,
  INDEX `tiendas_localidades_FK_1` (`id_localidad` ASC) VISIBLE,
  INDEX `tiendas_pedidos_FK_3` (`id_pedido` ASC) VISIBLE,
  INDEX `tiendas_empleados_FK_4` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `tiendas_localidades_FK_1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria_inma`.`localidades` (`id`),
  CONSTRAINT `tiendas_provincias_FK_2`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria_inma`.`provincias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`tipos_de_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`tipos_de_empleados` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_de_empleado` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`empleados` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_de_empleado` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_tienda` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre` VARCHAR(50) NOT NULL DEFAULT '0',
  `apellido_1` VARCHAR(50) NOT NULL DEFAULT '0',
  `apellido_2` VARCHAR(50) NOT NULL DEFAULT '0',
  `nif` VARCHAR(50) NOT NULL DEFAULT '0',
  `telefono` INT(9) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `empleados_tiendas_FK_1` (`id_tienda` ASC) VISIBLE,
  INDEX `empleados_tipo_de_empleados_FK_2` (`id_tipo_de_empleado` ASC) VISIBLE,
  CONSTRAINT `empleados_tiendas_FK_1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_inma`.`tiendas` (`id`),
  CONSTRAINT `empleados_tipo_de_empleados_FK_2`
    FOREIGN KEY (`id_tipo_de_empleado`)
    REFERENCES `pizzeria_inma`.`tipos_de_empleados` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`reparto_a_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`reparto_a_domicilio` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_de_empleado` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `fecha_entrega` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `reparto_a_domicilio_tipos_de_empleados_FK_1` (`id_tipo_de_empleado` ASC) VISIBLE,
  CONSTRAINT `reparto_a_domicilio_tipos_de_empleados_FK_1`
    FOREIGN KEY (`id_tipo_de_empleado`)
    REFERENCES `pizzeria_inma`.`tipos_de_empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`entrega_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`entrega_pedidos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_entrega` VARCHAR(50) NOT NULL,
  `reparto_a_domicilio_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `entrega_pedidos_reparto_a_domicilio_FK_1` (`reparto_a_domicilio_id` ASC) VISIBLE,
  CONSTRAINT `entrega_pedidos_reparto_a_domicilio_FK_1`
    FOREIGN KEY (`reparto_a_domicilio_id`)
    REFERENCES `pizzeria_inma`.`reparto_a_domicilio` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`pedidos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tienda` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `fecha_registro` DATETIME NOT NULL,
  `tipo_entrega` INT(11) UNSIGNED NOT NULL,
  `cantidad_producto` INT(11) UNSIGNED NOT NULL,
  `precio_total` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `id_cliente` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `pedido_cliente_FK_1` (`id_cliente` ASC) VISIBLE,
  INDEX `pedido_tipo_entrega_FK_2` (`tipo_entrega` ASC) VISIBLE,
  INDEX `pedidos_tiendas_FK_4` (`id_tienda` ASC) VISIBLE,
  CONSTRAINT `pedidos_cliente_FK_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria_inma`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pedidos_tiendas_FK_4`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_inma`.`tiendas` (`id`),
  CONSTRAINT `pedidos_tipo_entrega_FK_2`
    FOREIGN KEY (`tipo_entrega`)
    REFERENCES `pizzeria_inma`.`entrega_pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`tipos_de_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`tipos_de_productos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_tipo_producto` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`pizzas_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`pizzas_productos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_producto` INT(11) UNSIGNED NOT NULL,
  `id_categoria` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nombre_pizza` VARCHAR(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `pizzas_productos_categorias_FK_2` (`id_categoria` ASC) VISIBLE,
  INDEX `pizzas_productos_tipos_de_productos_FK_1` (`id_tipo_producto` ASC) VISIBLE,
  CONSTRAINT `pizzas_productos_categorias_FK_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pizzeria_inma`.`categorias` (`id`),
  CONSTRAINT `pizzas_productos_tipos_de_productos_FK_1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `pizzeria_inma`.`tipos_de_productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzeria_inma`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria_inma`.`productos` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo_producto` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id_pedido` INT(11) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL DEFAULT '',
  `descripcion` VARCHAR(255) NOT NULL DEFAULT '',
  `imagen` VARCHAR(255) NOT NULL DEFAULT '',
  `precio` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `producto_tipos_de_productos_FK_1` (`id_tipo_producto` ASC) VISIBLE,
  INDEX `productos_pedidos_FK_2` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `producto_tipos_de_productos_FK_1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `pizzeria_inma`.`tipos_de_productos` (`id`),
  CONSTRAINT `productos_pedidos_FK_2`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria_inma`.`pedidos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
